version: "3.8"

networks:
  G6T4-net:
    driver: bridge

volumes:
  rabbitmq_data:

services:
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - G6T4-net
    hostname: is213-esd-project-rabbitmq-1
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ###################################
  # Account: The Account SIMPLE MICROSERVICE
  ###################################  
  account:
    build:
      context: ./MS_Testing/Account_MS
      dockerfile: Account.Dockerfile
    image: m4rtinliu/account:v1
    networks:
      - G6T4-net
    container_name: account
    restart: always
    ports:
      - "5001:5001"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Listing: The Listing SIMPLE MICROSERVICE
  ###################################  
  listing:
    build:
      context: ./MS_Testing/Listing_MS
      dockerfile: Listing.Dockerfile
    image: m4rtinliu/listing:v1
    networks:
      - G6T4-net
    container_name: listing
    restart: always
    ports:
      - "5002:5002"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Cart: The Cart SIMPLE MICROSERVICE
  ###################################  
  cart:
    build:
      context: ./MS_Testing/Cart_MS
      dockerfile: Cart.Dockerfile
    image: m4rtinliu/cart:v1
    networks:
      - G6T4-net
    container_name: cart
    restart: always
    ports:
      - "5003:5003"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Payment: The Payment Atomic Service (Stripe Wrapper)
  ###################################  
  payment:
    build:
      context: ./MS_Testing/Payment_MS
      dockerfile: Payment.Dockerfile
    image: m4rtinliu/payment:v1
    networks:
      - G6T4-net
    container_name: payment
    restart: always
    ports:
      - "5005:5005"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Location: The Location SIMPLE MICROSERVICE
  ###################################  
  location:
    build:
      dockerfile: Dockerfile
    image: ckgoh2021/location:v1 
    networks:
      - G6T4-net
    container_name: location 
    restart: always
    ports:
      - "8080:8080"

  ###################################
  # Orders: The Orders SIMPLE MICROSERVICE
  ###################################  
  orders:
    build:
      context: ./MS_Testing/Orders_MS
      dockerfile: Orders.Dockerfile
    image: m4rtinliu/orders:v1
    networks:
      - G6T4-net
    container_name: orders
    restart: always
    ports:
      - "5004:5004"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Notification: The Notification Atomic Service (Twilio SendGrid Wrapper)
  ###################################  
  notification:
    build:
      context: ./MS_Testing/Notification_MS
      dockerfile: Notification.Dockerfile
    image: m4rtinliu/notification:v1
    networks:
      - G6T4-net
    depends_on:
      - rabbitmq
    container_name: notification
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672


  ###################################
  # Activity Log: The Activity Log Atomic Service (Twilio SendGrid Wrapper)
  ###################################  
  activitylog:
    build:
      context: ./MS_Testing/ActivityLog_MS
      dockerfile: activity_log.Dockerfile
    image: m4rtinliu/activitylog:v1
    networks:
      - G6T4-net
    depends_on:
      - rabbitmq
    container_name: activitylog
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672

  ###################################
  # Error Log: The Error Log Atomic Service (Twilio SendGrid Wrapper)
  ###################################  
  errorlog:
    build:
      context: ./MS_Testing/ErrorLog_MS
      dockerfile: error.Dockerfile
    image: m4rtinliu/errorlog:v1
    networks:
      - G6T4-net
    depends_on:
      - rabbitmq
    container_name: errorlog
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672

###################################################################### BREAK ######################################################################

  ###################################
  # BuyItem: The BuyItem COMPLEX MICROSERVICE (NEED ADD ENVIRONMENT)
  ###################################  
  buyitem:
    build:
      context: ./Complex_MS/BuyItem
      dockerfile: BuyItem.Dockerfile
    image: m4rtinliu/buyitem:v1
    networks:
      - G6T4-net
    container_name: buyitem
    restart: always
    depends_on:
      - account
      - listing
      - payment
      - cart
      - rabbitmq
      - orders
    ports:
      - "5200:5200"
    environment:
      account_URL: http://account:5001
      listing_URL: http://listing:5002
      cart_URL: http://cart:5003
      order_URL: http://orders:5004
      payment_URL: http://payment:5005
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672

  ###################################
  # LoginAccount: The LoginAccount COMPLEX MICROSERVICE (NEED ADD ENVIRONMENT)
  ###################################  
  loginaccount:
    build:
      context: ./Complex_MS/LoginAccount
      dockerfile: LoginAccount.Dockerfile
    # image: m4rtinliu/loginaccount:v1
    networks:
      - G6T4-net
    container_name: loginaccount
    restart: always
    depends_on:
      - account
      - listing
      - rabbitmq
      - location
    ports:
      - "5100:5100"
    environment:
      account_URL: http://account:5001
      location_URL: http://location:8080
      listing_URL: http://listing:5002
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672
      
  ###################################
  # ReturnItem: The ReturnItem COMPLEX MICROSERVICE (NEED ADD ENVIRONMENT)
  ###################################  
  returnitem:
    build:
      context: ./Complex_MS/ReturnItem
      dockerfile: ReturnItem.Dockerfile
    image: beatbeat04/returnitem:1.0
    networks:
      - G6T4-net
    container_name: returnitem
    restart: always
    depends_on:
      - account
      - orders
      - payment
      - rabbitmq
    ports:
      - "5300:5300"
    environment:
      account_URL: http://account:5001
      order_URL: http://orders:5004
      payment_URL: http://payment:5005
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672