version: "3.8"

# networks:
#   G6T4-net:
#     driver: bridge

volumes:
  rabbitmq_data:

services:
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    # networks:
    #   - G6T4-net
    hostname: esd-rabbit
    container_name: esd-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ###################################
  # Account: The Account SIMPLE MICROSERVICE
  ###################################  
  account:
    build:
      context: ./MS_Testing/Account_MS
      dockerfile: Account.Dockerfile
    image: mrtaooo/account:1.0
    # networks:
    #   - G6T4-net
    container_name: account
    restart: always
    ports:
      - "5001:5001"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Listing: The Listing SIMPLE MICROSERVICE
  ###################################  
  listing:
    build:
      context: ./MS_Testing/Listing_MS
      dockerfile: Listing.Dockerfile
    image: mrtaooo/listing:1.0
    # networks:
    #   - G6T4-net
    container_name: listing
    restart: always
    ports:
      - "5002:5002"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Cart: The Cart SIMPLE MICROSERVICE
  ###################################  
  cart:
    build:
      context: ./MS_Testing/Cart_MS
      dockerfile: Cart.Dockerfile
    image: mrtaooo/cart:1.0
    # networks:
    #   - G6T4-net
    container_name: cart
    restart: always
    ports:
      - "5003:5003"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Payment: The Payment SIMPLE MICROSERVICE
  ###################################  
  payment:
    build:
      context: ./MS_Testing/Payment_MS
      dockerfile: Payment.Dockerfile
    image: mrtaooo/payment:1.0
    # networks:
    #   - G6T4-net
    container_name: payment
    restart: always
    ports:
      - "5005:5005"
    environment:
      PYTHONUNBUFFERED: 1

  ###################################
  # Payment: The Payment SIMPLE MICROSERVICE
  ###################################  
  location:
    build:
      dockerfile: Dockerfile
    image: m4rtinliu/location:v1 
    # networks:
    #   - G6T4-net
    container_name: location 
    restart: always
    ports:
      - "8080:8080"
       

###################################################################### BREAK ######################################################################

  ###################################
  # BuyItem: The BuyItem COMPLEX MICROSERVICE (NEED ADD ENVIRONMENT)
  ###################################  
  buyitem:
    build:
      context: ./Complex_MS/BuyItem
      dockerfile: BuyItem.Dockerfile
    image: mrtaooo/buyitem:1.0
    # networks:
    #   - G6T4-net
    container_name: buyitem
    restart: always
    depends_on:
      - listing
      - payment
      - cart
      - rabbitmq
    ports:
      - "5200:5200"
    environment:
      # - location_URL: http://location:8080
      listing_URL: http://listing:5002
      cart_URL: http://cart:5003
      # - order_URL: http://order:5004
      payment_URL: http://payment:5005
      rabbit_host: rabbitmq
      PYTHONUNBUFFERED: 1

  ###################################
  # LoginAccount: The LoginAccount COMPLEX MICROSERVICE (NEED ADD ENVIRONMENT)
  ###################################  
  loginaccount:
    build:
      context: ./Complex_MS/LoginAccount
      dockerfile: LoginAccount.Dockerfile
    image: mrtaooo/loginaccount:1.0
    # networks:
    #   - G6T4-net
    container_name: loginaccount
    restart: always
    depends_on:
      - account
      - listing
      - rabbitmq
      # - Location
    ports:
      - "5100:5100"
    environment:
      rabbit_host: rabbitmq
      account_URL: http://account:5001
      # - location_URL: http://location:8080
      listing_URL: http://listing:5002
      PYTHONUNBUFFERED: 1

